# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'AnalysisWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QFrame, QHBoxLayout,
    QLabel, QLayout, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSpacerItem,
    QSpinBox, QTabWidget, QVBoxLayout, QWidget)

from pyqtgraph import (GraphicsLayoutWidget, PlotWidget)

class Ui_AnalysisWindow(object):
    def setupUi(self, AnalysisWindow):
        if not AnalysisWindow.objectName():
            AnalysisWindow.setObjectName(u"AnalysisWindow")
        AnalysisWindow.setEnabled(True)
        AnalysisWindow.resize(1425, 941)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AnalysisWindow.sizePolicy().hasHeightForWidth())
        AnalysisWindow.setSizePolicy(sizePolicy)
        AnalysisWindow.setAcceptDrops(True)
        AnalysisWindow.setAutoFillBackground(True)
        AnalysisWindow.setDocumentMode(False)
        AnalysisWindow.setTabShape(QTabWidget.TabShape.Rounded)
        AnalysisWindow.setDockNestingEnabled(False)
        AnalysisWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.actionHelp = QAction(AnalysisWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        self.actionLight = QAction(AnalysisWindow)
        self.actionLight.setObjectName(u"actionLight")
        self.actionLight.setCheckable(True)
        self.actionDark = QAction(AnalysisWindow)
        self.actionDark.setObjectName(u"actionDark")
        self.actionDark.setCheckable(True)
        self.actionM = QAction(AnalysisWindow)
        self.actionM.setObjectName(u"actionM")
        self.actionM.setCheckable(True)
        self.actionUm = QAction(AnalysisWindow)
        self.actionUm.setObjectName(u"actionUm")
        self.actionUm.setCheckable(True)
        self.actionNm = QAction(AnalysisWindow)
        self.actionNm.setObjectName(u"actionNm")
        self.actionNm.setCheckable(True)
        self.actionPm = QAction(AnalysisWindow)
        self.actionPm.setObjectName(u"actionPm")
        self.actionPm.setCheckable(True)
        self.actionNewWindow = QAction(AnalysisWindow)
        self.actionNewWindow.setObjectName(u"actionNewWindow")
        self.actionOpenFile = QAction(AnalysisWindow)
        self.actionOpenFile.setObjectName(u"actionOpenFile")
        self.actionPeaks = QAction(AnalysisWindow)
        self.actionPeaks.setObjectName(u"actionPeaks")
        self.centralwidget = QWidget(AnalysisWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(True)
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 0))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setAutoFillBackground(True)
        self.tab_ch1 = QWidget()
        self.tab_ch1.setObjectName(u"tab_ch1")
        self.verticalLayout_4 = QVBoxLayout(self.tab_ch1)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.main_qwt = QWidget(self.tab_ch1)
        self.main_qwt.setObjectName(u"main_qwt")
        sizePolicy.setHeightForWidth(self.main_qwt.sizePolicy().hasHeightForWidth())
        self.main_qwt.setSizePolicy(sizePolicy)
        self.main_hlay = QHBoxLayout(self.main_qwt)
        self.main_hlay.setObjectName(u"main_hlay")
        self.main_hlay.setContentsMargins(-1, -1, 1, -1)
        self.widgets_vlay = QVBoxLayout()
        self.widgets_vlay.setObjectName(u"widgets_vlay")
        self.spectraPlotWidget = PlotWidget(self.main_qwt)
        self.spectraPlotWidget.setObjectName(u"spectraPlotWidget")
        sizePolicy.setHeightForWidth(self.spectraPlotWidget.sizePolicy().hasHeightForWidth())
        self.spectraPlotWidget.setSizePolicy(sizePolicy)
        palette1 = QPalette()
        brush1 = QBrush(QColor(0, 0, 0, 0))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush1)
        self.spectraPlotWidget.setPalette(palette1)

        self.widgets_vlay.addWidget(self.spectraPlotWidget)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.temporalPlotWidget = PlotWidget(self.main_qwt)
        self.temporalPlotWidget.setObjectName(u"temporalPlotWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.temporalPlotWidget.sizePolicy().hasHeightForWidth())
        self.temporalPlotWidget.setSizePolicy(sizePolicy1)
        self.temporalPlotWidget.setAutoFillBackground(True)

        self.horizontalLayout.addWidget(self.temporalPlotWidget)

        self.boxPlotWidget = GraphicsLayoutWidget(self.main_qwt)
        self.boxPlotWidget.setObjectName(u"boxPlotWidget")
        sizePolicy1.setHeightForWidth(self.boxPlotWidget.sizePolicy().hasHeightForWidth())
        self.boxPlotWidget.setSizePolicy(sizePolicy1)
        self.boxPlotWidget.setAutoFillBackground(True)

        self.horizontalLayout.addWidget(self.boxPlotWidget)


        self.widgets_vlay.addLayout(self.horizontalLayout)


        self.main_hlay.addLayout(self.widgets_vlay)

        self.cfg_vlay = QVBoxLayout()
        self.cfg_vlay.setObjectName(u"cfg_vlay")
        self.fixTrace_hlay = QHBoxLayout()
        self.fixTrace_hlay.setObjectName(u"fixTrace_hlay")
        self.fixedTraces_vlay = QVBoxLayout()
        self.fixedTraces_vlay.setObjectName(u"fixedTraces_vlay")
        self.A_btn = QPushButton(self.main_qwt)
        self.A_btn.setObjectName(u"A_btn")
        self.A_btn.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.A_btn.sizePolicy().hasHeightForWidth())
        self.A_btn.setSizePolicy(sizePolicy2)
        self.A_btn.setMaximumSize(QSize(48, 16777215))
        palette2 = QPalette()
        brush2 = QBrush(QColor(139, 0, 0, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush2)
        brush3 = QBrush(QColor(255, 255, 255, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush3)
        brush4 = QBrush(QColor(170, 170, 170, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush4)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush2)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush3)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush4)
        brush5 = QBrush(QColor(139, 0, 0, 128))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush5)
        self.A_btn.setPalette(palette2)
        font = QFont()
        font.setFamilies([u"MS Sans Serif"])
        font.setPointSize(15)
        font.setBold(True)
        self.A_btn.setFont(font)
        self.A_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.A_btn.setAutoFillBackground(True)
        self.A_btn.setCheckable(True)
        self.A_btn.setChecked(False)
        self.A_btn.setAutoDefault(False)
        self.A_btn.setFlat(True)

        self.fixedTraces_vlay.addWidget(self.A_btn)

        self.B_btn = QPushButton(self.main_qwt)
        self.B_btn.setObjectName(u"B_btn")
        self.B_btn.setEnabled(True)
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.B_btn.sizePolicy().hasHeightForWidth())
        self.B_btn.setSizePolicy(sizePolicy3)
        self.B_btn.setMaximumSize(QSize(48, 16777215))
        palette3 = QPalette()
        brush6 = QBrush(QColor(0, 152, 0, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush6)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush3)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush4)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush6)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush3)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush4)
        brush7 = QBrush(QColor(0, 170, 0, 128))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush7)
        self.B_btn.setPalette(palette3)
        self.B_btn.setFont(font)
        self.B_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.B_btn.setAutoFillBackground(True)
        self.B_btn.setCheckable(True)
        self.B_btn.setChecked(False)
        self.B_btn.setFlat(True)

        self.fixedTraces_vlay.addWidget(self.B_btn)

        self.C_btn = QPushButton(self.main_qwt)
        self.C_btn.setObjectName(u"C_btn")
        self.C_btn.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.C_btn.sizePolicy().hasHeightForWidth())
        self.C_btn.setSizePolicy(sizePolicy3)
        self.C_btn.setMaximumSize(QSize(48, 16777215))
        palette4 = QPalette()
        brush8 = QBrush(QColor(0, 0, 188, 255))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush8)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush3)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush4)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush8)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush3)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush4)
        brush9 = QBrush(QColor(0, 0, 188, 128))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush9)
        self.C_btn.setPalette(palette4)
        self.C_btn.setFont(font)
        self.C_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.C_btn.setAutoFillBackground(True)
        self.C_btn.setCheckable(True)
        self.C_btn.setChecked(False)
        self.C_btn.setFlat(True)

        self.fixedTraces_vlay.addWidget(self.C_btn)

        self.D_btn = QPushButton(self.main_qwt)
        self.D_btn.setObjectName(u"D_btn")
        self.D_btn.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.D_btn.sizePolicy().hasHeightForWidth())
        self.D_btn.setSizePolicy(sizePolicy3)
        self.D_btn.setMaximumSize(QSize(48, 16777215))
        palette5 = QPalette()
        brush10 = QBrush(QColor(255, 170, 0, 255))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush10)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush3)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush4)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush10)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush3)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush4)
        brush11 = QBrush(QColor(255, 170, 0, 128))
        brush11.setStyle(Qt.BrushStyle.SolidPattern)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush11)
        self.D_btn.setPalette(palette5)
        self.D_btn.setFont(font)
        self.D_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.D_btn.setAutoFillBackground(True)
        self.D_btn.setCheckable(True)
        self.D_btn.setChecked(False)
        self.D_btn.setFlat(True)

        self.fixedTraces_vlay.addWidget(self.D_btn)

        self.E_btn = QPushButton(self.main_qwt)
        self.E_btn.setObjectName(u"E_btn")
        self.E_btn.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.E_btn.sizePolicy().hasHeightForWidth())
        self.E_btn.setSizePolicy(sizePolicy3)
        self.E_btn.setMaximumSize(QSize(48, 16777215))
        palette6 = QPalette()
        brush12 = QBrush(QColor(4, 150, 143, 255))
        brush12.setStyle(Qt.BrushStyle.SolidPattern)
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush3)
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush4)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush3)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush4)
        brush13 = QBrush(QColor(4, 150, 143, 128))
        brush13.setStyle(Qt.BrushStyle.SolidPattern)
        palette6.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush13)
        self.E_btn.setPalette(palette6)
        self.E_btn.setFont(font)
        self.E_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.E_btn.setAutoFillBackground(True)
        self.E_btn.setCheckable(True)
        self.E_btn.setChecked(False)
        self.E_btn.setFlat(True)

        self.fixedTraces_vlay.addWidget(self.E_btn)

        self.F_btn = QPushButton(self.main_qwt)
        self.F_btn.setObjectName(u"F_btn")
        self.F_btn.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.F_btn.sizePolicy().hasHeightForWidth())
        self.F_btn.setSizePolicy(sizePolicy3)
        self.F_btn.setMaximumSize(QSize(48, 16777215))
        palette7 = QPalette()
        brush14 = QBrush(QColor(114, 1, 124, 255))
        brush14.setStyle(Qt.BrushStyle.SolidPattern)
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush14)
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush3)
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush4)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush14)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush3)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush4)
        brush15 = QBrush(QColor(114, 1, 124, 128))
        brush15.setStyle(Qt.BrushStyle.SolidPattern)
        palette7.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush15)
        self.F_btn.setPalette(palette7)
        self.F_btn.setFont(font)
        self.F_btn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.F_btn.setAutoFillBackground(True)
        self.F_btn.setCheckable(True)
        self.F_btn.setChecked(False)
        self.F_btn.setFlat(True)

        self.fixedTraces_vlay.addWidget(self.F_btn)


        self.fixTrace_hlay.addLayout(self.fixedTraces_vlay)

        self.fixedLines_vlay = QVBoxLayout()
        self.fixedLines_vlay.setObjectName(u"fixedLines_vlay")
        self.line_A = QFrame(self.main_qwt)
        self.line_A.setObjectName(u"line_A")
        palette8 = QPalette()
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        self.line_A.setPalette(palette8)
        self.line_A.setAutoFillBackground(True)
        self.line_A.setFrameShadow(QFrame.Shadow.Raised)
        self.line_A.setFrameShape(QFrame.Shape.VLine)

        self.fixedLines_vlay.addWidget(self.line_A)

        self.line_B = QFrame(self.main_qwt)
        self.line_B.setObjectName(u"line_B")
        palette9 = QPalette()
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        self.line_B.setPalette(palette9)
        self.line_B.setAutoFillBackground(True)
        self.line_B.setFrameShadow(QFrame.Shadow.Raised)
        self.line_B.setFrameShape(QFrame.Shape.VLine)

        self.fixedLines_vlay.addWidget(self.line_B)

        self.line_C = QFrame(self.main_qwt)
        self.line_C.setObjectName(u"line_C")
        palette10 = QPalette()
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        self.line_C.setPalette(palette10)
        self.line_C.setAutoFillBackground(True)
        self.line_C.setFrameShadow(QFrame.Shadow.Raised)
        self.line_C.setFrameShape(QFrame.Shape.VLine)

        self.fixedLines_vlay.addWidget(self.line_C)

        self.line_D = QFrame(self.main_qwt)
        self.line_D.setObjectName(u"line_D")
        palette11 = QPalette()
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        self.line_D.setPalette(palette11)
        self.line_D.setAutoFillBackground(True)
        self.line_D.setFrameShadow(QFrame.Shadow.Raised)
        self.line_D.setFrameShape(QFrame.Shape.VLine)

        self.fixedLines_vlay.addWidget(self.line_D)

        self.line_E = QFrame(self.main_qwt)
        self.line_E.setObjectName(u"line_E")
        palette12 = QPalette()
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        self.line_E.setPalette(palette12)
        self.line_E.setAutoFillBackground(True)
        self.line_E.setFrameShadow(QFrame.Shadow.Raised)
        self.line_E.setFrameShape(QFrame.Shape.VLine)

        self.fixedLines_vlay.addWidget(self.line_E)

        self.line_F = QFrame(self.main_qwt)
        self.line_F.setObjectName(u"line_F")
        palette13 = QPalette()
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        self.line_F.setPalette(palette13)
        self.line_F.setAutoFillBackground(True)
        self.line_F.setFrameShadow(QFrame.Shadow.Raised)
        self.line_F.setFrameShape(QFrame.Shape.VLine)

        self.fixedLines_vlay.addWidget(self.line_F)


        self.fixTrace_hlay.addLayout(self.fixedLines_vlay)


        self.cfg_vlay.addLayout(self.fixTrace_hlay)

        self.verticalSpacer_2 = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.cfg_vlay.addItem(self.verticalSpacer_2)

        self.window_btn = QPushButton(self.main_qwt)
        self.window_btn.setObjectName(u"window_btn")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.window_btn.sizePolicy().hasHeightForWidth())
        self.window_btn.setSizePolicy(sizePolicy4)
        self.window_btn.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.window_btn.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.window_btn.setAutoFillBackground(False)
        icon = QIcon()
        icon.addFile(u"../img/apodization.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.window_btn.setIcon(icon)
        self.window_btn.setIconSize(QSize(36, 36))
        self.window_btn.setCheckable(False)
        self.window_btn.setAutoRepeat(False)
        self.window_btn.setAutoExclusive(False)
        self.window_btn.setAutoDefault(False)
        self.window_btn.setFlat(False)

        self.cfg_vlay.addWidget(self.window_btn)

        self.savgol_btn = QPushButton(self.main_qwt)
        self.savgol_btn.setObjectName(u"savgol_btn")
        sizePolicy4.setHeightForWidth(self.savgol_btn.sizePolicy().hasHeightForWidth())
        self.savgol_btn.setSizePolicy(sizePolicy4)
        self.savgol_btn.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        icon1 = QIcon()
        icon1.addFile(u"../img/savgol.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.savgol_btn.setIcon(icon1)
        self.savgol_btn.setIconSize(QSize(36, 36))

        self.cfg_vlay.addWidget(self.savgol_btn)

        self.mean_btn = QPushButton(self.main_qwt)
        self.mean_btn.setObjectName(u"mean_btn")
        sizePolicy4.setHeightForWidth(self.mean_btn.sizePolicy().hasHeightForWidth())
        self.mean_btn.setSizePolicy(sizePolicy4)
        self.mean_btn.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        icon2 = QIcon()
        icon2.addFile(u"../img/mean.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.mean_btn.setIcon(icon2)
        self.mean_btn.setIconSize(QSize(36, 36))

        self.cfg_vlay.addWidget(self.mean_btn)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.cfg_vlay.addItem(self.verticalSpacer)


        self.main_hlay.addLayout(self.cfg_vlay)


        self.verticalLayout_4.addWidget(self.main_qwt)

        self.tabWidget.addTab(self.tab_ch1, "")
        self.tab_ch2 = QWidget()
        self.tab_ch2.setObjectName(u"tab_ch2")
        self.verticalLayout_5 = QVBoxLayout(self.tab_ch2)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.tabWidget.addTab(self.tab_ch2, "")
        self.tab_ch3 = QWidget()
        self.tab_ch3.setObjectName(u"tab_ch3")
        self.verticalLayout_6 = QVBoxLayout(self.tab_ch3)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.tabWidget.addTab(self.tab_ch3, "")
        self.tab_ch4 = QWidget()
        self.tab_ch4.setObjectName(u"tab_ch4")
        self.verticalLayout_7 = QVBoxLayout(self.tab_ch4)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.tabWidget.addTab(self.tab_ch4, "")
        self.tab_merge = QWidget()
        self.tab_merge.setObjectName(u"tab_merge")
        self.verticalLayout_8 = QVBoxLayout(self.tab_merge)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.mergePlotWidget = PlotWidget(self.tab_merge)
        self.mergePlotWidget.setObjectName(u"mergePlotWidget")
        sizePolicy.setHeightForWidth(self.mergePlotWidget.sizePolicy().hasHeightForWidth())
        self.mergePlotWidget.setSizePolicy(sizePolicy)
        palette14 = QPalette()
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush1)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush1)
        self.mergePlotWidget.setPalette(palette14)

        self.verticalLayout_8.addWidget(self.mergePlotWidget)

        self.merge_hlay = QHBoxLayout()
        self.merge_hlay.setObjectName(u"merge_hlay")
        self.mergeCh1PlotWidget = PlotWidget(self.tab_merge)
        self.mergeCh1PlotWidget.setObjectName(u"mergeCh1PlotWidget")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.mergeCh1PlotWidget.sizePolicy().hasHeightForWidth())
        self.mergeCh1PlotWidget.setSizePolicy(sizePolicy5)
        self.mergeCh1PlotWidget.setMinimumSize(QSize(0, 200))
        self.mergeCh1PlotWidget.setMaximumSize(QSize(16777215, 200))
        palette15 = QPalette()
        palette15.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush1)
        palette15.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush1)
        self.mergeCh1PlotWidget.setPalette(palette15)

        self.merge_hlay.addWidget(self.mergeCh1PlotWidget)

        self.mergeCh2PlotWidget = PlotWidget(self.tab_merge)
        self.mergeCh2PlotWidget.setObjectName(u"mergeCh2PlotWidget")
        sizePolicy5.setHeightForWidth(self.mergeCh2PlotWidget.sizePolicy().hasHeightForWidth())
        self.mergeCh2PlotWidget.setSizePolicy(sizePolicy5)
        self.mergeCh2PlotWidget.setMinimumSize(QSize(0, 200))
        self.mergeCh2PlotWidget.setMaximumSize(QSize(16777215, 200))
        palette16 = QPalette()
        palette16.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush1)
        palette16.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush1)
        self.mergeCh2PlotWidget.setPalette(palette16)

        self.merge_hlay.addWidget(self.mergeCh2PlotWidget)

        self.mergeCh3PlotWidget = PlotWidget(self.tab_merge)
        self.mergeCh3PlotWidget.setObjectName(u"mergeCh3PlotWidget")
        sizePolicy5.setHeightForWidth(self.mergeCh3PlotWidget.sizePolicy().hasHeightForWidth())
        self.mergeCh3PlotWidget.setSizePolicy(sizePolicy5)
        self.mergeCh3PlotWidget.setMinimumSize(QSize(0, 200))
        self.mergeCh3PlotWidget.setMaximumSize(QSize(16777215, 200))
        palette17 = QPalette()
        palette17.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush1)
        palette17.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush1)
        self.mergeCh3PlotWidget.setPalette(palette17)

        self.merge_hlay.addWidget(self.mergeCh3PlotWidget)

        self.mergeCh4PlotWidget = PlotWidget(self.tab_merge)
        self.mergeCh4PlotWidget.setObjectName(u"mergeCh4PlotWidget")
        sizePolicy5.setHeightForWidth(self.mergeCh4PlotWidget.sizePolicy().hasHeightForWidth())
        self.mergeCh4PlotWidget.setSizePolicy(sizePolicy5)
        self.mergeCh4PlotWidget.setMinimumSize(QSize(0, 200))
        self.mergeCh4PlotWidget.setMaximumSize(QSize(16777215, 200))
        palette18 = QPalette()
        palette18.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush1)
        palette18.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush1)
        self.mergeCh4PlotWidget.setPalette(palette18)

        self.merge_hlay.addWidget(self.mergeCh4PlotWidget)


        self.verticalLayout_8.addLayout(self.merge_hlay)

        self.tabWidget.addTab(self.tab_merge, "")

        self.verticalLayout.addWidget(self.tabWidget)

        self.buttons_hlay = QHBoxLayout()
        self.buttons_hlay.setSpacing(5)
        self.buttons_hlay.setObjectName(u"buttons_hlay")
        self.buttons_hlay.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)
        self.buttons_hlay.setContentsMargins(10, 0, 10, 5)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.sr_lbl = QLabel(self.centralwidget)
        self.sr_lbl.setObjectName(u"sr_lbl")
        self.sr_lbl.setEnabled(False)
        self.sr_lbl.setAcceptDrops(False)
        self.sr_lbl.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.sr_lbl.setFrameShape(QFrame.Shape.NoFrame)
        self.sr_lbl.setFrameShadow(QFrame.Shadow.Plain)
        self.sr_lbl.setTextFormat(Qt.TextFormat.PlainText)
        self.sr_lbl.setScaledContents(False)

        self.verticalLayout_3.addWidget(self.sr_lbl)

        self.sr_spin = QSpinBox(self.centralwidget)
        self.sr_spin.setObjectName(u"sr_spin")
        self.sr_spin.setEnabled(False)
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.sr_spin.sizePolicy().hasHeightForWidth())
        self.sr_spin.setSizePolicy(sizePolicy6)
        self.sr_spin.setCursor(QCursor(Qt.CursorShape.IBeamCursor))
        self.sr_spin.setMinimum(100)
        self.sr_spin.setMaximum(5000)
        self.sr_spin.setValue(500)

        self.verticalLayout_3.addWidget(self.sr_spin)


        self.buttons_hlay.addLayout(self.verticalLayout_3)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Minimum)

        self.buttons_hlay.addItem(self.horizontalSpacer_2)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.cfg_lbl = QLabel(self.centralwidget)
        self.cfg_lbl.setObjectName(u"cfg_lbl")
        self.cfg_lbl.setEnabled(False)

        self.verticalLayout_2.addWidget(self.cfg_lbl)

        self.cfg_spin = QDoubleSpinBox(self.centralwidget)
        self.cfg_spin.setObjectName(u"cfg_spin")
        self.cfg_spin.setEnabled(False)
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.cfg_spin.sizePolicy().hasHeightForWidth())
        self.cfg_spin.setSizePolicy(sizePolicy7)
        self.cfg_spin.setCursor(QCursor(Qt.CursorShape.IBeamCursor))
        self.cfg_spin.setDecimals(0)

        self.verticalLayout_2.addWidget(self.cfg_spin)


        self.buttons_hlay.addLayout(self.verticalLayout_2)

        self.horizontalSpacer_4 = QSpacerItem(15, 20, QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)

        self.buttons_hlay.addItem(self.horizontalSpacer_4)

        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy8)
        self.line.setFrameShadow(QFrame.Shadow.Raised)
        self.line.setFrameShape(QFrame.Shape.VLine)

        self.buttons_hlay.addWidget(self.line)

        self.warning_hlay = QHBoxLayout()
        self.warning_hlay.setObjectName(u"warning_hlay")
        self.warning_hlay.setContentsMargins(6, -1, -1, -1)

        self.buttons_hlay.addLayout(self.warning_hlay)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.buttons_hlay.addItem(self.horizontalSpacer_3)

        self.continuous_hlay = QHBoxLayout()
        self.continuous_hlay.setObjectName(u"continuous_hlay")
        self.continuous_hlay.setContentsMargins(-1, -1, 5, -1)
        self.continuous_lbl = QLabel(self.centralwidget)
        self.continuous_lbl.setObjectName(u"continuous_lbl")

        self.continuous_hlay.addWidget(self.continuous_lbl)


        self.buttons_hlay.addLayout(self.continuous_hlay)

        self.horizontalSpacer = QSpacerItem(5, 20, QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)

        self.buttons_hlay.addItem(self.horizontalSpacer)

        self.save_btn = QPushButton(self.centralwidget)
        self.save_btn.setObjectName(u"save_btn")
        self.save_btn.setEnabled(True)
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy9)
        self.save_btn.setCursor(QCursor(Qt.CursorShape.ArrowCursor))

        self.buttons_hlay.addWidget(self.save_btn)

        self.clear_btn = QPushButton(self.centralwidget)
        self.clear_btn.setObjectName(u"clear_btn")
        self.clear_btn.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.clear_btn.setFlat(False)

        self.buttons_hlay.addWidget(self.clear_btn)

        self.stop_btn = QPushButton(self.centralwidget)
        self.stop_btn.setObjectName(u"stop_btn")
        sizePolicy9.setHeightForWidth(self.stop_btn.sizePolicy().hasHeightForWidth())
        self.stop_btn.setSizePolicy(sizePolicy9)
        self.stop_btn.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.stop_btn.setAutoFillBackground(True)
        self.stop_btn.setFlat(False)

        self.buttons_hlay.addWidget(self.stop_btn)


        self.verticalLayout.addLayout(self.buttons_hlay)

        AnalysisWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(AnalysisWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1425, 22))
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuConfigura_es = QMenu(self.menuBar)
        self.menuConfigura_es.setObjectName(u"menuConfigura_es")
        self.menuTema = QMenu(self.menuConfigura_es)
        self.menuTema.setObjectName(u"menuTema")
        self.menuUnidade_eixo_x = QMenu(self.menuConfigura_es)
        self.menuUnidade_eixo_x.setObjectName(u"menuUnidade_eixo_x")
        self.menuArquivo = QMenu(self.menuBar)
        self.menuArquivo.setObjectName(u"menuArquivo")
        AnalysisWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuArquivo.menuAction())
        self.menuBar.addAction(self.menuConfigura_es.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuHelp.addAction(self.actionHelp)
        self.menuConfigura_es.addAction(self.menuTema.menuAction())
        self.menuConfigura_es.addAction(self.menuUnidade_eixo_x.menuAction())
        self.menuConfigura_es.addAction(self.actionPeaks)
        self.menuTema.addAction(self.actionLight)
        self.menuTema.addAction(self.actionDark)
        self.menuUnidade_eixo_x.addAction(self.actionM)
        self.menuUnidade_eixo_x.addAction(self.actionUm)
        self.menuUnidade_eixo_x.addAction(self.actionNm)
        self.menuUnidade_eixo_x.addAction(self.actionPm)
        self.menuArquivo.addAction(self.actionNewWindow)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionOpenFile)

        self.retranslateUi(AnalysisWindow)

        self.tabWidget.setCurrentIndex(4)
        self.A_btn.setDefault(False)
        self.window_btn.setDefault(False)


        QMetaObject.connectSlotsByName(AnalysisWindow)
    # setupUi

    def retranslateUi(self, AnalysisWindow):
        AnalysisWindow.setWindowTitle(QCoreApplication.translate("AnalysisWindow", u"An\u00e1lise de dados", None))
        self.actionHelp.setText(QCoreApplication.translate("AnalysisWindow", u"ReadMe", None))
        self.actionLight.setText(QCoreApplication.translate("AnalysisWindow", u"Claro", None))
        self.actionDark.setText(QCoreApplication.translate("AnalysisWindow", u"Escuro", None))
        self.actionM.setText(QCoreApplication.translate("AnalysisWindow", u"m", None))
        self.actionUm.setText(QCoreApplication.translate("AnalysisWindow", u"\u03bcm", None))
        self.actionNm.setText(QCoreApplication.translate("AnalysisWindow", u"nm", None))
        self.actionPm.setText(QCoreApplication.translate("AnalysisWindow", u"pm", None))
        self.actionNewWindow.setText(QCoreApplication.translate("AnalysisWindow", u"Abrir nova janela", None))
        self.actionOpenFile.setText(QCoreApplication.translate("AnalysisWindow", u"Abrir arquivo", None))
        self.actionPeaks.setText(QCoreApplication.translate("AnalysisWindow", u"Encontrar picos", None))
#if QT_CONFIG(tooltip)
        self.A_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"Fixar espectro (1)", None))
#endif // QT_CONFIG(tooltip)
        self.A_btn.setText(QCoreApplication.translate("AnalysisWindow", u" A ", None))
#if QT_CONFIG(tooltip)
        self.B_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"Fixar espectro (2)", None))
#endif // QT_CONFIG(tooltip)
        self.B_btn.setText(QCoreApplication.translate("AnalysisWindow", u"B", None))
#if QT_CONFIG(tooltip)
        self.C_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"Fixar espectro (3)", None))
#endif // QT_CONFIG(tooltip)
        self.C_btn.setText(QCoreApplication.translate("AnalysisWindow", u"C", None))
#if QT_CONFIG(tooltip)
        self.D_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"Fixar espectro (4)", None))
#endif // QT_CONFIG(tooltip)
        self.D_btn.setText(QCoreApplication.translate("AnalysisWindow", u"D", None))
#if QT_CONFIG(tooltip)
        self.E_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"Fixar espectro (5)", None))
#endif // QT_CONFIG(tooltip)
        self.E_btn.setText(QCoreApplication.translate("AnalysisWindow", u"E", None))
#if QT_CONFIG(tooltip)
        self.F_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"Fixar espectro (6)", None))
#endif // QT_CONFIG(tooltip)
        self.F_btn.setText(QCoreApplication.translate("AnalysisWindow", u"F", None))
#if QT_CONFIG(tooltip)
        self.window_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"Janela (J)", None))
#endif // QT_CONFIG(tooltip)
        self.window_btn.setText("")
#if QT_CONFIG(tooltip)
        self.savgol_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"Filtro Savitzky-Golay (S)", None))
#endif // QT_CONFIG(tooltip)
        self.savgol_btn.setText("")
#if QT_CONFIG(tooltip)
        self.mean_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"M\u00e9dia espectral (M)", None))
#endif // QT_CONFIG(tooltip)
        self.mean_btn.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ch1), QCoreApplication.translate("AnalysisWindow", u"Canal 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ch2), QCoreApplication.translate("AnalysisWindow", u"Canal 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ch3), QCoreApplication.translate("AnalysisWindow", u"Canal 3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ch4), QCoreApplication.translate("AnalysisWindow", u"Canal 4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_merge), QCoreApplication.translate("AnalysisWindow", u"Merge", None))
        self.sr_lbl.setText(QCoreApplication.translate("AnalysisWindow", u"Intervalo m\u00ednimo entre aquisi\u00e7\u00f5es [ms]", None))
        self.cfg_lbl.setText(QCoreApplication.translate("AnalysisWindow", u"Tempo de exposi\u00e7\u00e3o [\u00b5s]", None))
        self.continuous_lbl.setText(QCoreApplication.translate("AnalysisWindow", u"Salvar continuamente todos os canais ativos", None))
#if QT_CONFIG(tooltip)
        self.save_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"(Ctrl+S)", None))
#endif // QT_CONFIG(tooltip)
        self.save_btn.setText(QCoreApplication.translate("AnalysisWindow", u"Confirmar Regi\u00e3o e Salvar", None))
#if QT_CONFIG(tooltip)
        self.clear_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"(Ctrl+L)", None))
#endif // QT_CONFIG(tooltip)
        self.clear_btn.setText(QCoreApplication.translate("AnalysisWindow", u"Limpar", None))
#if QT_CONFIG(tooltip)
        self.stop_btn.setToolTip(QCoreApplication.translate("AnalysisWindow", u"(Enter)", None))
#endif // QT_CONFIG(tooltip)
        self.stop_btn.setText(QCoreApplication.translate("AnalysisWindow", u"Parar", None))
        self.menuHelp.setTitle(QCoreApplication.translate("AnalysisWindow", u"Ajuda", None))
        self.menuConfigura_es.setTitle(QCoreApplication.translate("AnalysisWindow", u"Configura\u00e7\u00f5es", None))
        self.menuTema.setTitle(QCoreApplication.translate("AnalysisWindow", u"Tema", None))
        self.menuUnidade_eixo_x.setTitle(QCoreApplication.translate("AnalysisWindow", u"Unidade eixo-x", None))
        self.menuArquivo.setTitle(QCoreApplication.translate("AnalysisWindow", u"Arquivo", None))
    # retranslateUi

